<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:ccda="urn:hl7-org:v3" exclude-result-prefixes="ccda">
    
    <xsl:output method="xml" indent="yes" omit-xml-declaration="no" encoding="UTF-8"/>
    
    <!-- Root template matching the top-level ClinicalDocument -->
    <xsl:template match="/ccda:ClinicalDocument">
        <Message DatatypesVersion="20170715" TransportVersion="20170715" TransactionDomain="SCRIPT"
            TransactionVersion="20170715" StructuresVersion="20170715" ECLVersion="20170715"
            xsi:noNamespaceSchemaLocation="transport.xsd"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <Header>
                <!-- Static values for demonstration -->
                <To Qualifier="P"><xsl:value-of
                    select="ccda:informant/ccda:assignedEntity/ccda:id/@extension"/></To>
                <From Qualifier="D"><xsl:value-of
                    select="ccda:component/ccda:structuredBody/ccda:component/ccda:section/ccda:entry/ccda:observation/ccda:author/ccda:assignedAuthor/ccda:code/@code"/></From>
                <MessageID>50000000</MessageID>
                <SentTime>2024-03-30T10:00:23</SentTime>
                <SenderSoftware>
                    <SenderSoftwareDeveloper>NCPDP Conformance Tool</SenderSoftwareDeveloper>
                    <SenderSoftwareProduct>443</SenderSoftwareProduct>
                    <SenderSoftwareVersionRelease>12.1</SenderSoftwareVersionRelease>
                </SenderSoftware>
                <PrescriberOrderNumber>ORDMU201</PrescriberOrderNumber>
            </Header>
            <Body>
                <NewRx>
                    <ReturnReceipt>1</ReturnReceipt>
                    <Patient>
                        <HumanPatient>
                            <Identification>
                                <PatientAccountNumber>PBMC-ONC MU-6006F</PatientAccountNumber>
                            </Identification>
                            <Name>
                                <LastName>
                                    <xsl:value-of
                                        select="ccda:recordTarget/ccda:patientRole/ccda:patient/ccda:name/ccda:family"
                                    />
                                </LastName>
                                <FirstName>
                                    <xsl:value-of
                                        select="ccda:recordTarget/ccda:patientRole/ccda:patient/ccda:name/ccda:given"
                                    />
                                </FirstName>
                            </Name>
                            <Gender>
                                <xsl:value-of
                                    select="ccda:recordTarget/ccda:patientRole/ccda:patient/ccda:administrativeGenderCode/@code"
                                />
                            </Gender>
                            
                            <DateOfBirth>
                                <Date>1959-05-01</Date>
                            </DateOfBirth>
                            <Address>
                                <AddressLine1>
                                    <xsl:value-of
                                        select="ccda:recordTarget/ccda:patientRole/ccda:addr/ccda:streetAddressLine"
                                    />
                                </AddressLine1>
                                <City>
                                    <xsl:value-of
                                        select="ccda:recordTarget/ccda:patientRole/ccda:addr/ccda:city"
                                    />
                                </City>
                                <StateProvince>
                                    <xsl:value-of
                                        select="ccda:recordTarget/ccda:patientRole/ccda:addr/ccda:state"
                                    />
                                </StateProvince>
                                <PostalCode>
                                    <xsl:value-of
                                        select="ccda:recordTarget/ccda:patientRole/ccda:addr/ccda:postalCode"
                                    />
                                </PostalCode>
                                <CountryCode>US</CountryCode>
                            </Address>
                            <CommunicationNumbers>
                                <PrimaryTelephone>
                                    <Number>
                                        <xsl:value-of
                                            select="ccda:recordTarget/ccda:patientRole/ccda:telecom/@value"
                                        />
                                    </Number>
                                </PrimaryTelephone>
                            </CommunicationNumbers>
                        </HumanPatient>
                    </Patient>
                    <!-- Pharmacy details extraction -->
                    <Pharmacy>
                        <Identification>
                            <NCPDPID>1120188</NCPDPID>
                            <NPI><xsl:value-of
                                select="ccda:informant/ccda:assignedEntity/ccda:id/@extension"/></NPI>
                        </Identification>
                        <BusinessName>CVS Pharmacy</BusinessName>
                        <Address>
                            <AddressLine1>8970 S. Meridian St.</AddressLine1>
                            <City>Indianapolis</City>
                            <StateProvince>Marion County</StateProvince>
                            <PostalCode>46217</PostalCode>
                            <CountryCode>US</CountryCode>
                        </Address>
                        <CommunicationNumbers>
                            <PrimaryTelephone>
                                <Number>3177242302</Number>
                            </PrimaryTelephone>
                        </CommunicationNumbers>
                    </Pharmacy>
                    <!-- Prescriber details extraction -->
                    <Prescriber>
                        <NonVeterinarian>
                            <Identification>
                                <DEANumber>
                                    <xsl:value-of
                                        select="ccda:author/ccda:assignedAuthor/ccda:code/@code"/>
                                </DEANumber>
                                <NPI>
                                    <xsl:value-of
                                        select="ccda:component/ccda:structuredBody/ccda:component/ccda:section/ccda:entry/ccda:observation/ccda:author/ccda:assignedAuthor/ccda:code/@code"/>
                                </NPI>
                            </Identification>
                            <PracticeLocation>
                                <BusinessName>
                                    <xsl:value-of
                                        select="ccda:informant/ccda:assignedEntity/ccda:representedOrganization/ccda:name"
                                    />
                                </BusinessName>
                            </PracticeLocation>
                            <Name>
                                <LastName>
                                    <xsl:value-of
                                        select="ccda:author/ccda:assignedAuthor/ccda:assignedPerson/ccda:name/ccda:family"
                                    />
                                </LastName>
                                <FirstName>
                                    <xsl:value-of
                                        select="ccda:author/ccda:assignedAuthor/ccda:assignedPerson/ccda:name/ccda:given"
                                    />
                                </FirstName>
                            </Name>
                            <Address>
                                <AddressLine1>
                                    <xsl:value-of
                                        select="ccda:author/ccda:assignedAuthor/ccda:addr/ccda:streetAddressLine"
                                    />
                                </AddressLine1>
                                <City>
                                    <xsl:value-of
                                        select="ccda:author/ccda:assignedAuthor/ccda:addr/ccda:city"
                                    />
                                </City>
                                <StateProvince>
                                    <xsl:value-of
                                        select="ccda:author/ccda:assignedAuthor/ccda:addr/ccda:state"
                                    />
                                </StateProvince>
                                <PostalCode>
                                    <xsl:value-of
                                        select="ccda:author/ccda:assignedAuthor/ccda:addr/ccda:postalCode"
                                    />
                                </PostalCode>
                                <CountryCode>US</CountryCode>
                            </Address>
                            <CommunicationNumbers>
                                <PrimaryTelephone>
                                    <Number>
                                        <xsl:value-of
                                            select="ccda:author/ccda:assignedAuthor/ccda:telecom/@value"/>
                                    </Number>
                                </PrimaryTelephone>
                            </CommunicationNumbers>
                        </NonVeterinarian>
                    </Prescriber>
                    <!-- Medication details extraction -->
                    <MedicationPrescribed>
                        <DrugDescription>Atenolol 50 mg oral tablet</DrugDescription>
                        <DrugCoded>
                            <ProductCode>
                                <Code>197381</Code>
                                <Qualifier>ND</Qualifier>
                            </ProductCode>
                            <Strength>
                                <StrengthValue>
                                    <xsl:value-of
                                        select="ccda:component/ccda:structuredBody/ccda:component/ccda:section/ccda:entry/ccda:substanceAdministration/ccda:doseQuantity/@value"/>
                                </StrengthValue>
                                <StrengthForm>
                                    <Code>C15498</Code>
                                </StrengthForm>
                                    <StrengthUnitOfMeasure>
                                        <Code>C28253</Code>
                                    </StrengthUnitOfMeasure>
                            </Strength>
                            <DrugDBCode>
                                <Code>2.16.840.1.113883.6.88</Code>
                                <Qualifier>SCD</Qualifier>
                            </DrugDBCode>
                        </DrugCoded>
                        <Quantity>
                            <Value>
                                <xsl:value-of
                                    select="ccda:component/ccda:structuredBody/ccda:component/ccda:section/ccda:entry/ccda:substanceAdministration/ccda:doseQuantity/@value"
                                />
                            </Value>
                            <CodeListQualifier>38</CodeListQualifier>
                            <QuantityUnitOfMeasure>
                                <Code>C48542</Code>
                            </QuantityUnitOfMeasure>
                        </Quantity>
                        <WrittenDate>
                            <Date>2024-03-30</Date>
                        </WrittenDate>
                        <Substitutions>1</Substitutions>
                        <NumberOfRefills>2</NumberOfRefills>
                        <Diagnosis>
                            <ClinicalInformationQualifier>1</ClinicalInformationQualifier>
                            <Primary>
                                <Code>I10</Code>
                                <Qualifier>ABF</Qualifier>
                                <Description><xsl:value-of 
                                    select="ccda:component/ccda:structuredBody/ccda:component/ccda:section/ccda:entry/ccda:encounter/ccda:entryRelationship/ccda:act/ccda:code/@displayName"/>
                                </Description>
                                
                            </Primary>
                        </Diagnosis>
                        <Sig>
                            <SigText>Take 1 tablet oral route 1 per day morning</SigText>
                            <CodeSystem>
                                <SNOMEDVersion>2024-03-30</SNOMEDVersion>
                                <FMTVersion>19.12e</FMTVersion>
                            </CodeSystem>
                            <Instruction>
                                <DoseAdministration>
                                    <DoseDeliveryMethod>
                                        <Text>Take</Text>
                                        <Qualifier>SNOMED</Qualifier>
                                        <Code>419652001</Code>
                                    </DoseDeliveryMethod>
                                    <Dosage>
                                        <DoseQuantity>1</DoseQuantity>
                                        <DoseUnitOfMeasure>
                                            <Text>Tablet</Text>
                                            <Qualifier>DoseUnitOfMeasure</Qualifier>
                                            <Code>C48542</Code>
                                        </DoseUnitOfMeasure>
                                    </Dosage>
                                    <RouteOfAdministration>
                                        <Text>oral route</Text>
                                        <Qualifier>SNOMED</Qualifier>
                                        <Code>26643006</Code>
                                    </RouteOfAdministration>
                                </DoseAdministration>
                                <TimingAndDuration>
                                    <AdministrationTiming>
                                        <AdministrationTimingEvent>
                                            <Text>morning</Text>
                                            <Qualifier>SNOMED</Qualifier>
                                            <Code>73775008</Code>
                                        </AdministrationTimingEvent>
                                    </AdministrationTiming>
                                </TimingAndDuration>
                                <TimingAndDuration>
                                    <Frequency>
                                        <FrequencyNumericValue>
                                            <xsl:value-of
                                                select="ccda:component/ccda:structuredBody/ccda:component/ccda:section/ccda:entry/ccda:substanceAdministration/ccda:doseQuantity/@value"/>
                                        </FrequencyNumericValue>
                                        <FrequencyUnits>
                                            <Text>day</Text>
                                            <Qualifier>SNOMED</Qualifier>
                                            <Code>258703001</Code>
                                        </FrequencyUnits>
                                    </Frequency>
                                </TimingAndDuration>
                            </Instruction>
                        </Sig>
                        <PrescriberCheckedREMS>A</PrescriberCheckedREMS>
                    </MedicationPrescribed>
                </NewRx>
            </Body>
        </Message>
    </xsl:template>
    
</xsl:stylesheet>
